if (USE_CC_IECU2.0)
    message(STATUS "================  -] Eigen3 building IECU2.0 [-  ================")
    find_package(Eigen3 REQUIRED)
    include_directories(${EIGEN3_INCLUDE_DIR})
elseif (USE_CC_IECU3.1)
    message(STATUS "================  -] Eigen3 building IECU3.1 [-  ================")
    find_package(Eigen3 REQUIRED)
    include_directories(${EIGEN3_INCLUDE_DIR})
else ()
    message(STATUS "================  -] Eigen3 building x86-64 [-  ================")
    find_package(Eigen3 REQUIRED)
    include_directories(${EIGEN3_INCLUDE_DIR})
endif ()