if (USE_CC_IECU2.0)
    message(STATUS "================  -] Geographic building IECU2.0 [-  ================")
    set(GEOGRAPHICLIB_INCLUDE_DIRS ${THIRD_PART_PATH}/libGeographic/iecu2.0/include)
    include_directories(${GEOGRAPHICLIB_INCLUDE_DIRS})
    file(GLOB GEOGRAPHICLIB_LIBS ${THIRD_PART_PATH}/libGeographic/iecu2.0/lib/*.so*)
    list(APPEND ALL_LIBRARIES ${GEOGRAPHICLIB_LIBS})
elseif (USE_CC_IECU3.1)
    message(STATUS "================  -] Geographic building IECU3.1 [-  ================")
    set(GEOGRAPHICLIB_INCLUDE_DIRS ${THIRD_PART_PATH}/libGeographic/iecu3.1/include)
    include_directories(${GEOGRAPHICLIB_INCLUDE_DIRS})
    file(GLOB GEOGRAPHICLIB_LIBS ${THIRD_PART_PATH}/libGeographic/iecu3.1/lib/*.so*)
    list(APPEND ALL_LIBRARIES ${GEOGRAPHICLIB_LIBS})
else ()
    message(STATUS "================  -] Geographic building x86-64 [-  ================")
    set(GEOGRAPHICLIB_INCLUDE_DIRS ${PROJECT_SOURCE_DIR}/3rdparty/geographiclib-1.49/include)
    include_directories(${GEOGRAPHICLIB_INCLUDE_DIRS})
    file(GLOB GEOGRAPHICLIB_LIBS ${PROJECT_SOURCE_DIR}/3rdparty/geographiclib-1.49/lib/*.so*)
    list(APPEND ALL_LIBRARIES ${GEOGRAPHICLIB_LIBS})
endif ()