if (USE_CC_IECU2.0)
    message(STATUS "================  -] lcm building IECU2.0 [-  ================")
    set(LCM_INCLUDE_DIRS ${THIRD_PART_PATH}/lcm-1.3.0-saic/iecu2.0/include)
    include_directories(${LCM_INCLUDE_DIRS})
    # message("lcm: ${LCM_INCLUDE_DIRS}")
    file(GLOB LCM_LIBS ${THIRD_PART_PATH}/lcm-1.3.0-saic/iecu2.0/lib/liblcm.so)
    list(APPEND ALL_LIBRARIES ${LCM_LIBS})
elseif (USE_CC_IECU3.1)
    message(STATUS "================  -] lcm building IECU3.1 [-  ================")
    set(LCM_INCLUDE_DIRS ${THIRD_PART_PATH}/lcm-1.3.0-saic/iecu3.1/include)
    include_directories(${LCM_INCLUDE_DIRS})
    # message("lcm: ${LCM_INCLUDE_DIRS}")
    file(GLOB LCM_LIBS ${THIRD_PART_PATH}/lcm-1.3.0-saic/iecu3.1/lib/liblcm.so)
    list(APPEND ALL_LIBRARIES ${LCM_LIBS})
else ()
    message(STATUS "================  -] lcm building x86-64 [-  ================")
    set(LCM_INCLUDE_DIRS ${PROJECT_SOURCE_DIR}/3rdparty/lcm-1.3.0-saic/include)
    include_directories(${LCM_INCLUDE_DIRS})
    file(GLOB LCM_LIBS ${PROJECT_SOURCE_DIR}/3rdparty/lcm-1.3.0-saic/lib/*.so)
    list(APPEND ALL_LIBRARIES ${LCM_LIBS})

endif ()
