if (USE_CC_IECU2.0)
    message(STATUS "================  -] rclcpp building IECU2.0 [-  ================")
    find_package(rclcpp REQUIRED)
    include_directories(${rclcpp_INCLUDE_DIRS})
    list(APPEND ALL_LIBRARIES ${rclcpp_LIBRARIES})
elseif (USE_CC_IECU3.1)
    message(STATUS "================  -] rclcpp building IECU3.1 [-  ================")
    find_package(rclcpp REQUIRED)
    include_directories(${rclcpp_INCLUDE_DIRS})
    list(APPEND ALL_LIBRARIES ${rclcpp_LIBRARIES})
else ()
    message(STATUS "================  -] rclcpp building x86-64 [-  ================")
    find_package(rclcpp REQUIRED)
    include_directories(${rclcpp_INCLUDE_DIRS})
    list(APPEND ALL_LIBRARIES ${rclcpp_LIBRARIES})
endif ()