if (USE_CC_IECU2.0)
  message(STATUS "================  -] building IECU2.0 [-  ================")
  find_package(rosbag2_storage REQUIRED)
  include_directories(${rosbag2_storage_INCLUDE_DIRS})
  list(APPEND ALL_LIBRARIES ${rosbag2_storage_LIBRARIES})
else ()
  message(STATUS "================  -] building x86-64 [-  ================")
  find_package(rosbag2_storage REQUIRED)
  include_directories(${rosbag2_storage_INCLUDE_DIRS})
  list(APPEND ALL_LIBRARIES ${rosbag2_storage_LIBRARIES})
endif()