if (USE_CC_IECU2.0)
    message(STATUS "================  -] sensor_msgs building IECU2.0 [-  ================")
    find_package(sensor_msgs REQUIRED)
    include_directories(${sensor_msgs_INCLUDE_DIRS})
    list(APPEND ALL_LIBRARIES ${sensor_msgs_LIBRARIES})
elseif (USE_CC_IECU3.1)
    message(STATUS "================  -] sensor_msgs building IECU3.1 [-  ================")
    find_package(sensor_msgs REQUIRED)
    include_directories(${sensor_msgs_INCLUDE_DIRS})
    list(APPEND ALL_LIBRARIES ${sensor_msgs_LIBRARIES})
else ()
    message(STATUS "================  -] sensor_msgs building x86-64 [-  ================")
    find_package(sensor_msgs REQUIRED)
    include_directories(${sensor_msgs_INCLUDE_DIRS})
    list(APPEND ALL_LIBRARIES ${sensor_msgs_LIBRARIES})

endif ()