if (USE_CC_IECU2.0)
  message(STATUS "================  -] building IECU2.0 [-  ================")
  #find_package (Sophus REQUIRED)
  set(Sophus_INCLUDE_DIRS ${PROJECT_SOURCE_DIR}/3rdparty/Sophus/iecu2.0/include)
  include_directories(${Sophus_INCLUDE_DIRS})
  list(APPEND ALL_TARGET_LIBRARIES ${Sophus_LIBRARIES})

else ()
  message(STATUS "================  -] building x86-64 [-  ================")
  #find_package (Sophus REQUIRED)
  set(Sophus_INCLUDE_DIRS ${PROJECT_SOURCE_DIR}/3rdparty/Sophus/include)
  include_directories(${Sophus_INCLUDE_DIRS})
  list(APPEND ALL_TARGET_LIBRARIES ${Sophus_LIBRARIES})

endif()