/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <lcm/lcm_coretypes.h>

#ifndef __IBEO_OBJECTS_hpp__
#define __IBEO_OBJECTS_hpp__

#include "HEADER.hpp"


class IBEO_OBJECTS
{
    public:
        HEADER     header;

        int64_t    time_pub;

        int16_t    nObjectsNumber;

        int16_t    gnObjectID[256];

        uint8_t    gbObjectClass[256];

        int32_t    gnClassificationAge[256];

        int8_t     gnClassificationCertainty[256];

        int8_t     gnNumberOfContourPoints[256];

        float      gfAbsoluteVelocityX[256];

        float      gfAbsoluteVelocityY[256];

        float      gfAbsoluteVelocitySigmaX[256];

        float      gfAbsoluteVelocitySigmaY[256];

        float      gfRelativeVelocityX[256];

        float      gfRelativeVelocityY[256];

        float      gfRelativeVelocitySigmaX[256];

        float      gfRelativeVelocitySigmaY[256];

        float      gfObjectBoxCenterX[256];

        float      gfObjectBoxCenterY[256];

        float      gfObjectBoxOrientation[256];

        float      gfObjectBoxOrientationSigma[256];

        float      gfObjectBoxSizeX[256];

        float      gfObjectBoxSizeY[256];

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "IBEO_OBJECTS"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int IBEO_OBJECTS::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = (int64_t)getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int IBEO_OBJECTS::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int IBEO_OBJECTS::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t IBEO_OBJECTS::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* IBEO_OBJECTS::getTypeName()
{
    return "IBEO_OBJECTS";
}

int IBEO_OBJECTS::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = this->header._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->time_pub, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->nObjectsNumber, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->gnObjectID[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __byte_encode_array(buf, offset + pos, maxlen - pos, &this->gbObjectClass[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->gnClassificationAge[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &this->gnClassificationCertainty[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &this->gnNumberOfContourPoints[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->gfAbsoluteVelocityX[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->gfAbsoluteVelocityY[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->gfAbsoluteVelocitySigmaX[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->gfAbsoluteVelocitySigmaY[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->gfRelativeVelocityX[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->gfRelativeVelocityY[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->gfRelativeVelocitySigmaX[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->gfRelativeVelocitySigmaY[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->gfObjectBoxCenterX[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->gfObjectBoxCenterY[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->gfObjectBoxOrientation[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->gfObjectBoxOrientationSigma[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->gfObjectBoxSizeX[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->gfObjectBoxSizeY[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int IBEO_OBJECTS::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = this->header._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->time_pub, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->nObjectsNumber, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->gnObjectID[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __byte_decode_array(buf, offset + pos, maxlen - pos, &this->gbObjectClass[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->gnClassificationAge[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &this->gnClassificationCertainty[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &this->gnNumberOfContourPoints[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->gfAbsoluteVelocityX[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->gfAbsoluteVelocityY[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->gfAbsoluteVelocitySigmaX[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->gfAbsoluteVelocitySigmaY[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->gfRelativeVelocityX[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->gfRelativeVelocityY[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->gfRelativeVelocitySigmaX[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->gfRelativeVelocitySigmaY[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->gfObjectBoxCenterX[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->gfObjectBoxCenterY[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->gfObjectBoxOrientation[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->gfObjectBoxOrientationSigma[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->gfObjectBoxSizeX[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->gfObjectBoxSizeY[0], 256);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int IBEO_OBJECTS::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += this->header._getEncodedSizeNoHash();
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += __int16_t_encoded_array_size(NULL, 1);
    enc_size += __int16_t_encoded_array_size(NULL, 256);
    enc_size += __byte_encoded_array_size(NULL, 256);
    enc_size += __int32_t_encoded_array_size(NULL, 256);
    enc_size += __int8_t_encoded_array_size(NULL, 256);
    enc_size += __int8_t_encoded_array_size(NULL, 256);
    enc_size += __float_encoded_array_size(NULL, 256);
    enc_size += __float_encoded_array_size(NULL, 256);
    enc_size += __float_encoded_array_size(NULL, 256);
    enc_size += __float_encoded_array_size(NULL, 256);
    enc_size += __float_encoded_array_size(NULL, 256);
    enc_size += __float_encoded_array_size(NULL, 256);
    enc_size += __float_encoded_array_size(NULL, 256);
    enc_size += __float_encoded_array_size(NULL, 256);
    enc_size += __float_encoded_array_size(NULL, 256);
    enc_size += __float_encoded_array_size(NULL, 256);
    enc_size += __float_encoded_array_size(NULL, 256);
    enc_size += __float_encoded_array_size(NULL, 256);
    enc_size += __float_encoded_array_size(NULL, 256);
    enc_size += __float_encoded_array_size(NULL, 256);
    return enc_size;
}

uint64_t IBEO_OBJECTS::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == IBEO_OBJECTS::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, (void*)IBEO_OBJECTS::getHash };

    uint64_t hash = 0x12ab6920779d3ab7LL +
         HEADER::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

#endif
